# Conda Environment
# https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file

name: metal-snake
dependencies:
    - rust
